packages:
  - packages/*
  - apps/*
overrides:
  typescript: 6.0.3
injectWorkspacePackages: true
allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
  workerd: true
#per-project
minimumReleaseAge: 10080 # 7 days
blockExoticSubdeps: true
trustPolicy: no-downgrade

