[d1_databases]
DB = { 
  binding = "DB", 
  database_name = "db_clawfeehouse", 
  preview_database_name = "db_clawfeehouse_preview" 
}

[env.production]
vars = { NODE_ENV = "production" }

[env.development]
vars = { NODE_ENV = "development" }