-- Migration 035: Add data column to user_profiles (no-op)
--
-- This migration originally added a missing 'data' column to user_profiles.
-- Migration 032 has since been updated to include the column in the CREATE TABLE,
-- so on fresh installs the column already exists by the time this runs.
--
-- The ALTER TABLE has been removed to prevent "duplicate column name: data" errors
-- during fresh installs (GitHub issue #771). Wrangler's migration runner does not
-- gracefully handle duplicate column errors like the runtime MigrationService does.
--
-- Existing databases that ran the old 032 (without the data column) get the column
-- added at runtime by the core MigrationService, which skips duplicate-column errors.
--
-- This file is kept as a no-op so that wrangler's migration tracking remains
-- consistent (it tracks migrations by filename).
SELECT 1;
